# ============================================
# PNPM Workspace Configuration
# ============================================
# https://pnpm.io/workspaces

packages:
  # Apps (frontend)
  - 'apps/*'
  
  # Packages (backend, shared)
  - 'packages/*'
  
  # Parser (отдельный сервис)
  - 'parser'
